CREATE TABLE IF NOT EXISTS public.basegeneralcostos (
    op TEXT,
    orden TEXT,
    orden_vieja_nueva TEXT,
    clasificacion_de_la_orden TEXT,
    cc TEXT,
    scc TEXT,
    b TEXT,
    especialidad TEXT,
    cod_uen TEXT,
    uen TEXT,
    sub_indice TEXT,
    estado TEXT,
    apertura_siigo TEXT,
    cierre_siigo TEXT,
    descripcion_producto_terminado TEXT,
    codigo_pp TEXT,
    codigo_pt TEXT,
    categoria_sub_indice TEXT,
    cliente TEXT,
    ubicacion TEXT,
    estado_base_contrato TEXT,
    apertura_base_contratos TEXT,
    cierre_base_contratos TEXT,
    ingeniero TEXT,
    ot_planta TEXT,
    nit TEXT,
    uen_fact TEXT,
    vr_contratado DOUBLE PRECISION,
    descripcion TEXT,
    cajas_menores DOUBLE PRECISION
);
